### ISSUE TITLE
Published to npmjs like other bs-packages

### ISSUE THREAD

**Issue by bernalrs** [lpalmes/bs-material-ui#3]
Hi, 

Would be great if this can be published to npm.js like other bs-packages ?

Thanks

**Comment by lpalmes** [comment]
Hey @bernalrs, i've was using this project as a git dependency, but you are totally right, i will upload it to npm, thanks for your interest on the project!

**Comment by bernalrs** [comment]
Great thanks, I am about to start a project and I use material-ui, I think we can help each other.

**Comment by lpalmes** [comment]
Of course, i'm trying to get feature parity with the [v1](https://material-ui-next.com/), if you are able to send pr for missing components and fixes that would be awesome, i'm using it for a project of mine, so slowly i've been adding components to it.
